### ISSUE TITLE
Handling typography in responsive web

### ISSUE THREAD

**Issue by francesyun** [opentable/design-tokens#142]
Brought up by @char1e5 (Charles works on works on RestRef, which is responsive down to mobile) 

What's the recommended strategy for bringing in typography tokens on responsive web? Because the token names for desktop-typography and mobile-typography appear to be the same (font-size-small, etc), when they are both imported, the names will collide. 

@mannionaco, is the idea that desktop-typography font stack will be used across the board for web (including responsive web at mobile size)? If so, this point is moot.

**Comment by char1e5** [comment]
Great 👍 Thanks @francesyun 
Same questions. I just put under this PR - https://github.com/opentable/design-tokens/pull/97

**Comment by lastquestion** [comment]
So I guess I have *two parts* to this discussion.

This is all my personal opinion which was largely formed today after trying to update `ot-react-ui` components to use the two new modules.  So please feel free to discuss and let me know what you think.

First, the two modules and consuming them.

* `otkit-typography-desktop` defines the font brand name, values for each font grouping (heading, body, subtext, etc.). Also, it defines the font fallback stack, which is really only for web, but that's alright - the only platform we support on desktop is web.

* `otkit-typography-mobile` also defines the font brand name, values for each font grouping -- but the actual pixel values may be different !! I also expect that eventually we will define a font fallback stack for mobile web as well, which will likely take on different values - as we may rely more broadly on device fonts. But in any case the high level point is the names of the groupings are the same, but may have different values. For example, `heading-xlarge-line-height` might be different.

When using them using CSS-modules, you can rename when importing so you don't have collisions, if you expect to use them in the same file: https://github.com/css-modules/postcss-icss-values#aliases. I tested this earlier this year when playing around with CSS modules, and if you're using the postcss+webpack build path it should work.


Second, writing shared components that need to rely on typography values - e.g. stuff in https://github.com/opentable/ot-react-ui-components/, basically. 

For these, I think that we may we need to build styling separately. One CSS module would import from `desktop`, the other from `mobile`. The built outputs would both be packaged in the NPM module. It's a little similar to node versus browser built outputs, I think. I'm not quite sure exactly how this would be picked up in the hosting app yet. But it should at least allow the flexibility for hosting apps to support responsive or not. To be honest, of course, I haven't completely thought through all the details here, but I will absolutely open an issue in `ot-react-ui` and link it from here later today.

**Comment by karuto** [comment]
### Why do we split the tokens
The primary reason we split the tokens by platform / screen sizes is because they are different. The desktop typography token isn't supposed to support mobile web. On a related note, going forward we are treating individual typography tokens as standalone entities without references to a shared group of aliases, which means we are moving away from the "shared values" + "deltas" mindset at the implementation level for better visibility (for designers) and fine grained control.

### Strategy for responsive microsites on consuming multiple tokens
@lastquestion gave some very good suggestions. You can import with aliases to avoid conflicts. We did not put platform prefixes for the variables because we believe within the context of the token it is redundant to do so.

### Distribution of font groups
This is what I'm thinking next. Now that we have updated individual typography variables, we should have some shared way of distributing the assembled font groups, so that each consumer microsite does not have to repeat this process. @char1e5 how does your team currently plan to use these tokens' values in a responsive context? Would be really interesting to collect more data on that front.

**Comment by char1e5** [comment]
Thanks for your detailed explanations about **WHAT**, **HOW** and **WHY** @lastquestion @karuto . Now I get better understanding of this changes 👍 

Here is my 2 cents. Correct me if I'm wrong here
- *"The primary reason we split the tokens by platform / screen sizes is because they are different."*
👍 Responsive web apps looks different as well. We choose to use different tokens based on screen size. Separating design tokens by platforms makes sense from design respective.
- *"Consuming from two modules"* 
👍  If two modules hold tokens, we don't have any choice here. Adding alias to each tokens is not a hard task for sure.
🤔  It's just a little annoying (not supported originally from the universal package). If iOS or Android using this token, are we going to create new ones for them? Should this be the original problem we want to resolve by unifying design tokens? Keep them the same as much as possible in the future.
- *writing shared components that need to rely on typography values. ... build styling separately*
👍`ot-react-ui` should be flexible enough to support responsive or not. 
- *"distribution of font groups"*
👍 Sharing font groups are great. 
Two parts in my thought. 
One is `font-family` (Saw this in desktop token). Second, `font-face` and other stuff seems not belongs to design tokens. It should be their own package like [eyeglass-otwebui-typography](https://github.com/opentable/eyeglass-otwebui-typography/blob/master/sass/_typography.scss). This package's output is css, scss for the entire web app, not same as other tokens. We use that in the same way of other microsite - [R3 _typography.scss](https://github.com/opentable/restref-site/blob/master/app/styles/partials/_typography.scss)

Overall, I agreed on desktop/mobile token approach. Thanks to share your thoughts on this.

**Comment by matteofigus** [comment]
Hi @char1e5, I tried to reply to some of the questions:

` If iOS or Android using this token, are we going to create new ones for them?`
Yes, with design we agreed that in case we'll create otkit-typography-ios and otkit-typography-android
`Should this be the original problem we want to resolve by unifying design tokens?`
In principle is true but not for all the tokens. The format is otkit-token if the token is the same everywhere (like colors) or otkit-token-platform if there are differences. In this perspective, when that is the case, we have one of each platform (that's why we deprecated the otkit-typography).
`Second, font-face and other stuff seems not belongs to design tokens`
The goal for design tokens is to encode design decisions. The exact order for when the fonts are listed with fallbacks, and the name of the brand font are actually design choices and the goal is to distribute them here. If then you want to wrap them in a sass or css module, you should be able to. If you note, we also don't distribute as token the static font http url, as that is an engineering choice.

Hopefully makes sense? What do you think?

**Comment by char1e5** [comment]
Thanks @matteofigus Sounds good to me 👍

**Comment by lastquestion** [comment]
I would also say that remember, unification only is a goal if the actual root values, system, decision, etc. is itself unified.

If design believes that on certain platforms, we need different values, decisions, etc. then there's nothing to "unify!", and forcing things to be "universal" actually causes a lot of issues. 

For the distribution of "font groups", I think it's a good idea to try and stop repeating this across microsites, but actually, it's not too bad even if we do define the groups many times. I'm having a hard time thinking of a clean, low overhead way to do this. So if anyone has ideas, do mention them :-)

**Comment by karuto** [comment]
I'm going to close this thread since it seems like we reached agreement. If there are any objections feel free to write below.
