### ISSUE TITLE
Packages don't have main files

### ISSUE THREAD

**Issue by morrisallison** [opentable/design-tokens#25]
The published packages don't have main entries. To use the packages in Node, the modules need to be imported directly like:

```js
import otThemeColors from 'ottheme-colors/token.common';
```

**Comment by lastquestion** [comment]
@nickbalestra , I don't think we ever really plan on having multiple files inside each token NPM package, right?

In which case, it's kinda weird not to just publish the JS files as `index`. 

Also, here's what we are writing in CSS module land:

```
@value color-gray-primary, color-gray-utility from 'otkit-colors/token.cssmodules.css';
```

https://github.com/opentable/start-page-nodejs/blob/develop/restaurant-profile/src/components/tag/styles.css#L1

which seems a little verbose, as well. 

I'm excited about having tokens published, and IMHO this is a detail that doesn't bother me much, but I don't really see us likely needing to publish multiple files from a token module. I guess I feel that the token modules should be quite compact and scoped.

**Comment by nickbalestra** [comment]
Thanks very much for the good points @morrisallison and @lastquestion. 

Here I'll try to share with you some of the rationale we followed when building our tokens:

Token should support multiple format and be  as tech agnostic as possible, as that is their main objective. 
Putting the `common.js` format as the main `index` will assume 2 things:

1 - Semantically, as main in a manifest mean, `common.js` will be assumed as the main file, while there should no implicit main format for tokens.
2 - JavaScript wise this will also assume that `common.js` will be the defacto js module system supported (what about amd, es6 modules, mjs.. <- more on this later..)

Morrison mention node, but actually the import syntax in the given example is not really supported by node as node doesn't support es6 module syntax natively. The route chosen for the Node.js EP, and currently accepted by the Node.js CTC for ES Modules is detection via filename extension: `.mjs`. Also in this context the chosen solution is pretty agnostic and safe.

I agree that this is slightly more verbose 😅 , we tried to [document](https://github.com/opentable/design-tokens/tree/master/OTKit#otkit-tokens) that as much as possible but please feel free to open PR's to improve any parts of that if that is not clear enough.

The same apply for the cssmodules format that Lin is mentioning: that is `*.cssmodules.css` and not simply `.css`, as cssmodules's `css` is not strictly valid `css` this make it clear for consumers and allows in the future to perhaps have pure `*.css` format token as well (hey css variables, looking at you here). That explain why [I've added cssmodules.css support ](https://github.com/salesforce-ux/theo/pull/111)in this way

Not touching an index file, allows us to be in a much better place to avoid issues related on braking contracts with various consumers as each consumer need to explicitly mention the target format.

Finally you want to have a build system that works the same for any format you want to add, support and include in the published package. At the moment we can support all of the[ those formats ](https://github.com/salesforce-ux/theo#available-formats)

I would love to hear if you have any suggestion that allows not bake any of those mentioned assumptions in the token itself , while supporting a flexible build system that works and treats each format in the same way. 

Hope that helps

**Comment by morrisallison** [comment]
> Morrison mention node, but actually the import syntax in the given example is not really supported by node as node doesn't support es6 module syntax natively.

You're playing with semantics. My point is that we can't simply import from `'ottheme-colors'` directly.

> JavaScript wise this will also assume that common.js will be the defacto js module system supported. **[...]** Not touching an index file, allows us to be in a much better place to avoid issues related on braking contracts with various consumers as each consumer need to explicitly mention the target format.

I understand that one of goals of this project is to be as consumer agnostic as possible. However, this is being achieved by not directly supporting any consumers. It doesn't need to be that way, and I'd argue that it shouldn't be.

As a compromise, I'll suggest adding a `/node` directory containing an `index.js` and a `index.mjs`. Then we can import via `'ottheme-colors/node'` and let Node decide which file to import. From a consumer perspective, that's a much more stable contract than importing a file directly.

**Comment by lastquestion** [comment]
@nickbalestra @morrisallison For me, targeting a file whose path never changes is actually pretty ok. I like the idea of having equal formats, and providing support looking forward for different module targets. But, I'm old school, and never much liked `index.js` `global headers` anyway.

This is based upon a perhaps incorrect assumption, which is that the file is always called `token.something`, and the `something` is what changes. In other words, we never generate multiple files in a token module. Which isn't specified in the docs. But I would say it would be bananas if that wasn't true. That is something I'm pretty opinionated about. @nickbalestra 

For CSS, which I'm much more focused on right now, I'm pretty sure that we can override the resolve logic manually if we need to and get the right behavior. e.g, `@import ... from 'otkit-colors'` would actually expand into `otkit-colors/tokens.cssmodules.css`. And that makes sense, because by the time `@import` is happening, we know for sure we're in CSS-modules and can make that substitution. But, I don't see much pain to directly write out the path there. If more engineers complain, I will look into trying to improve that aliasing.

For JS, from what I read of `.mjs`, having `main: ./index` - without file extension! - will target the right file both ways. I also think that we are basically either `commonjs` or `es6` in the future, and therefore `tokens.js` or `tokens.mjs` makes sense and is an ok optimization. It is not as elegant, because it breaks symmetry with `css` files, for which we absolutely need the extra `cssmodules` or `plaincss`. Once we get real life tooling with `.mjs` support, I suspect by then `main` as a field is going to be less common, because many packages will want to target multiple targets, especially isomorphic code. So I think something like webpack's https://webpack.js.org/configuration/resolve/#resolve-mainfields will become standardized. So I guess I'm proposing waiting for the industry to settle, because I believe this is a common problem and concern, and keep `main` empty.

**Comment by nickbalestra** [comment]
Ditto @lastquestion. Good point on mentioning that the file format (`token.format`) is not well documented, I'll make sure to update docs ([ottheme](https://github.com/opentable/design-tokens/blob/master/OTTheme/README.md), [otkit](https://github.com/opentable/design-tokens/blob/master/OTKit/README.md) and main docs) and close this Issue once done.

**Comment by morrisallison** [comment]
@lastquestion 

> For me, targeting a file whose path never changes is actually pretty ok.

That's pretty much the key. Package names can't change, file names can. Awkwardness aside, if the file names don't change, then it's fine.

**Comment by nickbalestra** [comment]
Yup @morrisallison thats the idea, I'll document that.

**Comment by char1e5** [comment]
@nickbalestra @lastquestion @morrisallison 
Thanks to share these awesome ideas 👍  
First, I should admit that I didn't read much about current design token implementation with [Theo available-formats](https://github.com/salesforce-ux/theo#available-formats) before this discussion happened 😞 
Looking at this design tokens in a broader view can really understand the symmetry of each platform. 
> Theo consumes Design Token files which are a central location to store design related information such as colors, fonts, widths, animations, etc. These raw values can then be transformed and formatted to meet the needs of any platform.

But as token consumers in JS, we were assuming to import `ottheme-colors` without path like other npm packages earlier. Now, token npm packages are just carriers for `cssmodules`, `scss` and `common.js`, etc (most likely only have web related formats because of npm). 
If the token file name won't change, we could even write a wrapper and not import this package directly every time. Here I think we just want to have this been supported natively by taking advantage of `main` field (for `common.js`or `es6 modules`). Clearly, there are some flaws as well.

I agreed that documentation or brown bags will help a lot to clear these questions or concerns. 
Thanks Again 😄
