### ISSUE TITLE
Border widths

### ISSUE THREAD

**Issue by karuto** [opentable/design-tokens#311]
I know that we didn't put the entire border declaration into the OTKit-borders token because we haven't decided how to let tokens reference each other yet.

But how about widths? I commonly see 1px, 2px etc. Is there a guideline on this? @mannionaco

**Comment by mannionaco** [comment]
1px ash-lighter (d8d9db) is default for border buttons
2px red (da3743) is hover and select state for border buttons, this is the only representation that I'm aware of that 2px should be being use for. Do you have additional use cases?

[Button documentation](https://opentable.invisionapp.com/share/ZJKD87TKF8V#/screens/319609755_buttons) from the [OTKit wiki](https://wiki.otcorp.opentable.com/display/UX/OTKit#OTKit-Componentdocumentation)

**Comment by karuto** [comment]
I think that's the 2 use cases I found. I see them a lot. Although 1px d8d9db is also quite commonly used as border-bottom and dividers.

Do you think we should just provide a grouping then? Maybe for now, use the hex directly instead of figuring out how to reference the OTKit-colors? Like so:

```
border-default:
  value: "1px solid #d8d9db"

border-hover:
  value: "2px solid #da3743"
```

I suck at names you should come up with names that make sense in design system, but you get my idea? @mannionaco

**Comment by mannionaco** [comment]
i see, so there may be confusion when applying "border" as "dividing line"

i think it makes sense that they are separate:

dividing-line-default:
value "1px ash-lighter or hex value representation"

border-default:
value "1px ash-lighter or hex value representation"

border-hover (since this is being consumed in web i think it makes most sense to use words that are common, i use "active" as a global name vs by platform, but that's just me"
value "2px ash-lighter or hex value representation"

border-selected (not sure if we need this? - probably make sense though, it's clear)
value "1px ash-lighter or hex value representation"

what do you think?

**Comment by karuto** [comment]
Hey Kellen @mannionaco, sorry I dropped the ball on this one. I think we still need to proceed with this approach, to put the entire divider definition into the borders token. Let me know if you have a more updated spec now, we can work together on this.

**Comment by mannionaco** [comment]
@karuto i'll tag you in (abstract) the refined button styles so that our naming is clear. border-hover still applies and shouldn't be "active" as I reference above.

border-selected = 2px red (not what i listed above)

**Comment by karuto** [comment]
Thanks @mannionaco will talk to you in person about this

**Comment by karuto** [comment]
Resolved by https://github.com/opentable/design-tokens/pull/428, moving the discussion over.
