### ISSUE TITLE
Why CommonJS?

### ISSUE THREAD

**Issue by morewry** [opentable/design-tokens#61]
Dunno if I maybe missed this conversation, but how did you decide which formats to build? There is existing Sass code, so I assume that's why SCSS is one format. The new efforts are using CSS Modules, so that's why on that format. 

But why is CommonJS the only JavaScript format? My current understanding of the UI components is that they will be using ES Modules, not CommonJS modules? I'd expect in that case for ES Module sto be one of the formats in which the tokens are available.

**Comment by matteofigus** [comment]
We added this format because C4 was already doing Styled Components with the new Restref Site and we wanted to allow them to integrate DT. This was a bit before we agreed about using CSS modules. I think the plan agreed with the team was to remove this format once they would migrate to CSS modules.

Perhaps, we could add in the docs that people shouldn't be encouraged to do use that format as it's going to be deprecated.

**Comment by cbeley** [comment]
@matteofigus Little confused.  It sounds like @matteofigus is just asking why we export commonJS instead of an ES module.

I would assume the only reason for commonjs modules is for backwards compatibility?  babel lets us import from commonjs modules anyway, so everything's pretty transparent.

It definitely wouldn't be a good idea to not allow these variables to be access in JS though.  While rare, there are occasionally times where those values are needed in JS land.

**Comment by lastquestion** [comment]
Woops I hit the wrong button.

**Comment by morewry** [comment]
@cbeley Yeah, that was mainly what I was wondering. And, by extension, if there were any thoughts on whether we'd be likely to add ES Module or maybe start doing what you mentioned and using theo-loader on the raw JSON format.

**Comment by lastquestion** [comment]
I see no problem adding ES modules support to the build system here, but - as alluded to by @matteofigus - there shouldn't be much need to do that if you have CSS module imports working. But for example maybe there's need for legacy code to directly import and use the token values (dialog box, iframe, e.g.) and then you could import via ES or CommonJS.

**Comment by morewry** [comment]
Okay, clarifying questions, @lastquestion. In your comment are you assuming that the tokens will mostly only be used within the CSS Modules? If so, is that because that's the only places their values will likely be needed? Or is it because you, for example, get a map of from the imported CSS Module within the JS portion of a component?

**Comment by lastquestion** [comment]
@morewry the latter. According to https://github.com/css-modules/postcss-icss-values#importing-value-in-js, which is the library that we are using in start, it should just work.
